name: openpgp
description: library for use OpenPGP with support for android and ios, macOS, linux, web and hover
version: 1.0.0-rc1
homepage: https://github.com/jerson/flutter-openpgp

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.0
  ffi: ^0.1.3
  protobuf: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.jerson.openpgp
        pluginClass: OpenpgpPlugin
      ios:
        pluginClass: OpenpgpPlugin
      web:
        pluginClass: OpenpgpPlugin
        fileName: web/openpgp_web.dart
      linux:
        pluginClass: OpenpgpPlugin
      macos:
        pluginClass: OpenpgpPlugin
      windows:
        pluginClass: OpenpgpPlugin